on:
  push:
    branches: ["backend"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      - name: Grant excute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ${{ env.working-directory }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: "./backend/build/libs/*.jar"
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create distribute
        run: mkdir ~/dist

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Show structure of download files
        run: |
          ls -alh dist
      
      - name: Deploy use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          rm: true
          source: "dist/*.jar"
          target: "/home/eoeo/api_server/"
          strip_components: 1
      
